language: node_js

node_js:
  - "8"

install:
  - npm install
  - npm run build

script: echo 'skip test' # Skip `yarn test`

deploy:
  local_dir: ./dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
